-- 코드를 입력하세요
SELECT * 
FROM FOOD_PRODUCT 
WHERE PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT)


-- 변수를 이용하면 조금 더 깔끔하게 풀 수 있다.
SET @MAX_PRICE = (SELECT MAX(PRICE) FROM FOOD_PRODUCT);

SELECT *
FROM FOOD_PRODUCT
WHERE PRICE = (SELECT @MAX_PRICE := MAX(PRICE) FROM FOOD_PRODUCT)
