-- 코드를 입력하세요
WITH BEST_REVIEW AS
(SELECT M.MEMBER_ID, M.MEMBER_NAME, COUNT(*) AS CNT, 
RANK() OVER(ORDER BY COUNT(*) DESC) AS RANKING
FROM MEMBER_PROFILE M
JOIN REST_REVIEW R ON M.MEMBER_ID = R.MEMBER_ID
GROUP BY M.MEMBER_ID
ORDER BY CNT DESC)
SELECT T.MEMBER_NAME, R.REVIEW_TEXT, DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW R
JOIN BEST_REVIEW T
ON R.MEMBER_ID = T.MEMBER_ID
WHERE T.RANKING = 1
ORDER BY REVIEW_DATE, REVIEW_TEXT;