-- 코드를 입력하세요
SELECT b.CATEGORY as CATEGORY, SUM(a.SALES) as TOTAL_SALES
FROM BOOK_SALES a LEFT JOIN BOOK b ON a.BOOK_ID = b.BOOK_ID
WHERE DATE_FORMAT(a.SALES_DATE, '%Y-%m') = '2022-01'
GROUP BY CATEGORY
ORDER BY CATEGORY