-- 코드를 입력하세요
SELECT g.TITLE, g.BOARD_ID, r.REPLY_ID, r.WRITER_ID, r.CONTENTS, DATE_FORMAT(r.CREATED_DATE, '%Y-%m-%d')
FROM USED_GOODS_BOARD g 
INNER JOIN USED_GOODS_REPLY r
USING(BOARD_ID)
WHERE date_format(g.CREATED_DATE, '%Y-%m-%d') LIKE '2022-10%'
ORDER BY r.CREATED_DATE, g.TITLE;

